-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/ContentTranslation/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cx_translations (
  translation_id SERIAL NOT NULL,
  translation_source_title TEXT NOT NULL,
  translation_target_title TEXT NOT NULL,
  translation_source_language TEXT NOT NULL,
  translation_target_language TEXT NOT NULL,
  translation_source_revision_id INT DEFAULT NULL,
  translation_target_revision_id INT DEFAULT NULL,
  translation_source_url TEXT NOT NULL,
  translation_target_url TEXT DEFAULT NULL,
  translation_status TEXT DEFAULT NULL,
  translation_start_timestamp TIMESTAMPTZ NOT NULL,
  translation_last_updated_timestamp TIMESTAMPTZ NOT NULL,
  translation_progress TEXT NOT NULL,
  translation_started_by INT DEFAULT NULL,
  translation_last_update_by INT DEFAULT NULL,
  translation_cx_version SMALLINT DEFAULT 1,
  PRIMARY KEY(translation_id)
);

CREATE UNIQUE INDEX cx_translation_ref ON cx_translations (
  translation_source_title, translation_source_language,
  translation_target_language, translation_started_by
);

CREATE INDEX cx_translation_languages ON cx_translations (
  translation_source_language, translation_target_language,
  translation_status
);

CREATE INDEX cx_translation_target_title ON cx_translations (translation_target_title);


CREATE TABLE cx_translators (
  translator_user_id INT NOT NULL,
  translator_translation_id INT NOT NULL,
  PRIMARY KEY(
    translator_user_id, translator_translation_id
  )
);


CREATE TABLE cx_lists (
  cxl_id SERIAL NOT NULL,
  cxl_type INT DEFAULT 0,
  cxl_owner INT NOT NULL,
  cxl_public SMALLINT NOT NULL,
  cxl_start_time TIMESTAMPTZ DEFAULT NULL,
  cxl_end_time TIMESTAMPTZ DEFAULT NULL,
  cxl_name TEXT NOT NULL,
  cxl_info TEXT DEFAULT NULL,
  PRIMARY KEY(cxl_id)
);

CREATE UNIQUE INDEX cx_lists_relevant ON cx_lists (
  cxl_type, cxl_public, cxl_start_time,
  cxl_end_time
);


CREATE TABLE cx_suggestions (
  cxs_list_id INT NOT NULL, cxs_source_language TEXT NOT NULL,
  cxs_target_language TEXT DEFAULT NULL,
  cxs_title TEXT NOT NULL
);

CREATE INDEX cx_suggestions_by_lang ON cx_suggestions (
  cxs_list_id, cxs_source_language,
  cxs_target_language
);


CREATE TABLE cx_corpora (
  cxc_id SERIAL NOT NULL,
  cxc_translation_id INT NOT NULL,
  cxc_section_id TEXT NOT NULL,
  cxc_origin TEXT NOT NULL,
  cxc_sequence_id INT DEFAULT NULL,
  cxc_timestamp TIMESTAMPTZ DEFAULT NULL,
  cxc_content TEXT DEFAULT NULL,
  PRIMARY KEY(cxc_id)
);

CREATE UNIQUE INDEX cx_corpora_unique ON cx_corpora (
  cxc_translation_id, cxc_origin, cxc_section_id,
  cxc_timestamp
);


CREATE TABLE cx_notification_log (
  cxn_id SERIAL NOT NULL,
  cxn_date TIMESTAMPTZ NOT NULL,
  cxn_newest TIMESTAMPTZ NOT NULL,
  cxn_wiki_id TEXT DEFAULT NULL,
  PRIMARY KEY(cxn_id)
);

CREATE INDEX cxn_wiki_id_newest ON cx_notification_log (cxn_wiki_id, cxn_newest);


CREATE TABLE cx_significant_edits (
  cxse_id SERIAL NOT NULL,
  cxse_global_user_id INT NOT NULL,
  cxse_page_wikidata_id INT NOT NULL,
  cxse_language TEXT NOT NULL,
  cxse_wiki_family INT NOT NULL,
  cxse_page_title TEXT NOT NULL,
  cxse_section_titles TEXT NOT NULL,
  cxse_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(cxse_id)
);

CREATE UNIQUE INDEX cx_significant_edits_page ON cx_significant_edits (
  cxse_global_user_id, cxse_page_wikidata_id,
  cxse_language, cxse_wiki_family
);


CREATE TABLE cx_section_translations (
  cxsx_id SERIAL NOT NULL,
  cxsx_translation_id INT NOT NULL,
  cxsx_section_id TEXT NOT NULL,
  cxsx_source_section_title TEXT NOT NULL,
  cxsx_target_section_title TEXT NOT NULL,
  cxsx_translation_status SMALLINT DEFAULT NULL,
  cxsx_translation_progress TEXT NOT NULL,
  cxsx_translation_start_timestamp TIMESTAMPTZ NOT NULL,
  cxsx_translation_last_updated_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(cxsx_id)
);

CREATE UNIQUE INDEX cx_sx_sections ON cx_section_translations (
  cxsx_translation_id, cxsx_section_id
);
