CREATE TABLE /*_*/cx_notification_log (
    -- Notification log id - autogenerated
    cxn_id int primary key auto_increment,
    -- Date when notification script was run
    cxn_date varchar(14) binary not null,
    -- Newest draft which was updated with this script run
    cxn_newest varchar(14) binary not null
) /*$wgDBTableOptions*/;

CREATE UNIQUE INDEX /*i*/cx_notification_log_index ON /*_*/cx_notification_log (
    cxn_date,
    cxn_newest
);
