-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/ContentTranslation/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cx_section_translations (
  cxsx_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cxsx_translation_id INT UNSIGNED NOT NULL,
  cxsx_section_id VARBINARY(30) NOT NULL,
  cxsx_source_section_title VARBINARY(512) NOT NULL,
  cxsx_target_section_title VARBINARY(512) NOT NULL,
  UNIQUE INDEX cx_sx_sections (
    cxsx_translation_id, cxsx_section_id
  ),
  PRIMARY KEY(cxsx_id)
) /*$wgDBTableOptions*/;
