-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/ContentTranslation/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cx_significant_edits (
  cxse_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cxse_global_user_id INT UNSIGNED NOT NULL,
  cxse_page_wikidata_id INT UNSIGNED NOT NULL,
  cxse_language VARBINARY(36) NOT NULL,
  cxse_wiki_family INT UNSIGNED NOT NULL,
  cxse_page_title VARBINARY(255) NOT NULL,
  cxse_section_titles MEDIUMBLOB NOT NULL,
  cxse_timestamp BINARY(14) NOT NULL,
  UNIQUE INDEX cx_significant_edits_page (
    cxse_global_user_id, cxse_page_wikidata_id,
    cxse_language, cxse_wiki_family
  ),
  PRIMARY KEY(cxse_id)
) /*$wgDBTableOptions*/;
