-- This table stores recent significant edits by a user in any wiki.
-- Only the 10 latest edits by each user are stored.
-- This table is used to identify potential section suggestions for
-- the "recentedit" entrypoint
CREATE TABLE /*_*/cx_significant_edits (
    -- edit id. Autogenerated.
    cxse_id int unsigned not null primary key auto_increment,
    -- Global user id of the user that did the edit
    cxse_global_user_id int unsigned not null,
    -- Wikidata id (qid) of the page that was edited without the "Q" prefix
    cxse_page_wikidata_id int unsigned not null,
    -- Language code of the page that was edited. This language is used as
    -- source language to fetch section suggestions from cxserver,
    -- when user visits this page that they have edited, in another language.
    cxse_language varbinary(36) not null,
    -- Wiki family of the wiki in which the edit occurred
    -- This field is not currently used, but is added for future expansion of
    -- Content Translation to non-Wikipedia wikis
    cxse_wiki_family int unsigned not null,
    -- Title of the page that was edited. This title is used as
    -- source title to fetch section suggestions from cxserver,
    -- when user visits this page that they have edited, in another language.
    cxse_page_title varbinary(255) not null,
    -- Titles of the sections that were edited. Stores a JSON string
    -- representing an array of strings
    cxse_section_titles mediumblob not null,
    -- Timestamp of this edit
    cxse_timestamp binary(14) not null
) /*$wgDBTableOptions*/;

CREATE UNIQUE INDEX /*i*/cx_significant_edits_page ON /*_*/cx_significant_edits (
    cxse_global_user_id,
    cxse_page_wikidata_id,
    cxse_language,
    cxse_wiki_family
);
