-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentTranslation/sql/abstractSchemaChanges/patch-new-fields-to-cx_section_translations.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/cx_section_translations
ADD  COLUMN cxsx_translation_status SMALLINT DEFAULT NULL;
ALTER TABLE  /*_*/cx_section_translations
ADD  COLUMN cxsx_translation_progress BLOB NOT NULL;
ALTER TABLE  /*_*/cx_section_translations
ADD  COLUMN cxsx_translation_start_timestamp BLOB NOT NULL;
ALTER TABLE  /*_*/cx_section_translations
ADD  COLUMN cxsx_translation_last_updated_timestamp BLOB NOT NULL;