-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-cx_suggestions-index-source_language_title.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__cx_suggestions AS
SELECT
  cxs_list_id,
  cxs_source_language,
  cxs_target_language,
  cxs_title
FROM /*_*/cx_suggestions;

DROP TABLE /*_*/cx_suggestions;


CREATE TABLE /*_*/cx_suggestions (
  cxs_list_id INTEGER NOT NULL, cxs_source_language BLOB NOT NULL,
  cxs_target_language BLOB DEFAULT NULL,
  cxs_title BLOB NOT NULL
);

INSERT INTO /*_*/cx_suggestions (
  cxs_list_id, cxs_source_language,
  cxs_target_language, cxs_title
)
SELECT
  cxs_list_id,
  cxs_source_language,
  cxs_target_language,
  cxs_title
FROM
  /*_*/__temp__cx_suggestions;

DROP TABLE /*_*/__temp__cx_suggestions;

CREATE INDEX cx_suggestions_by_lang ON /*_*/cx_suggestions (
  cxs_list_id, cxs_source_language,
  cxs_target_language
);

CREATE INDEX cx_suggestions_source_language_title ON /*_*/cx_suggestions (cxs_source_language, cxs_title);
