-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-cx_translators-unique-to-pk.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX cx_translation_translators;
CREATE TEMPORARY TABLE /*_*/__temp__cx_translators AS
SELECT  translator_user_id,  translator_translation_id
FROM  /*_*/cx_translators;
DROP  TABLE  /*_*/cx_translators;
CREATE TABLE  /*_*/cx_translators (    translator_user_id INTEGER NOT NULL,    translator_translation_id INTEGER NOT NULL,    PRIMARY KEY(      translator_user_id, translator_translation_id    )  );
INSERT INTO  /*_*/cx_translators (    translator_user_id, translator_translation_id  )
SELECT  translator_user_id,  translator_translation_id
FROM  /*_*/__temp__cx_translators;
DROP  TABLE /*_*/__temp__cx_translators;