-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/ContentTranslation/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cx_translations (
  translation_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  translation_source_title BLOB NOT NULL,
  translation_target_title BLOB NOT NULL,
  translation_source_language BLOB NOT NULL,
  translation_target_language BLOB NOT NULL,
  translation_source_revision_id INTEGER UNSIGNED DEFAULT NULL,
  translation_target_revision_id INTEGER UNSIGNED DEFAULT NULL,
  translation_source_url BLOB NOT NULL,
  translation_target_url BLOB DEFAULT NULL,
  translation_status TEXT DEFAULT NULL,
  translation_start_timestamp BLOB NOT NULL,
  translation_last_updated_timestamp BLOB NOT NULL,
  translation_progress BLOB NOT NULL,
  translation_started_by INTEGER DEFAULT NULL,
  translation_last_update_by INTEGER DEFAULT NULL,
  translation_cx_version SMALLINT UNSIGNED DEFAULT 1
);

CREATE UNIQUE INDEX cx_translation_ref ON /*_*/cx_translations (
  translation_source_title, translation_source_language,
  translation_target_language, translation_started_by
);

CREATE INDEX cx_translation_languages ON /*_*/cx_translations (
  translation_source_language, translation_target_language,
  translation_status
);

CREATE INDEX cx_translation_target_title ON /*_*/cx_translations (translation_target_title);


CREATE TABLE /*_*/cx_translators (
  translator_user_id INTEGER NOT NULL,
  translator_translation_id INTEGER NOT NULL,
  PRIMARY KEY(
    translator_user_id, translator_translation_id
  )
);


CREATE TABLE /*_*/cx_lists (
  cxl_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cxl_type INTEGER DEFAULT 0, cxl_owner INTEGER NOT NULL,
  cxl_public SMALLINT NOT NULL, cxl_start_time BLOB DEFAULT NULL,
  cxl_end_time BLOB DEFAULT NULL, cxl_name BLOB NOT NULL,
  cxl_info BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX cx_lists_relevant ON /*_*/cx_lists (
  cxl_type, cxl_public, cxl_start_time,
  cxl_end_time
);


CREATE TABLE /*_*/cx_suggestions (
  cxs_list_id INTEGER NOT NULL, cxs_source_language BLOB NOT NULL,
  cxs_target_language BLOB DEFAULT NULL,
  cxs_title BLOB NOT NULL
);

CREATE INDEX cx_suggestions_by_lang ON /*_*/cx_suggestions (
  cxs_list_id, cxs_source_language,
  cxs_target_language
);


CREATE TABLE /*_*/cx_corpora (
  cxc_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cxc_translation_id INTEGER NOT NULL,
  cxc_section_id BLOB NOT NULL, cxc_origin BLOB NOT NULL,
  cxc_sequence_id INTEGER DEFAULT NULL,
  cxc_timestamp BLOB DEFAULT NULL, cxc_content BLOB DEFAULT NULL
);

CREATE UNIQUE INDEX cx_corpora_unique ON /*_*/cx_corpora (
  cxc_translation_id, cxc_origin, cxc_section_id,
  cxc_timestamp
);


CREATE TABLE /*_*/cx_notification_log (
  cxn_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cxn_date BLOB NOT NULL, cxn_newest BLOB NOT NULL,
  cxn_wiki_id BLOB DEFAULT NULL
);

CREATE INDEX cxn_wiki_id_newest ON /*_*/cx_notification_log (cxn_wiki_id, cxn_newest);


CREATE TABLE /*_*/cx_significant_edits (
  cxse_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cxse_global_user_id INTEGER UNSIGNED NOT NULL,
  cxse_page_wikidata_id INTEGER UNSIGNED NOT NULL,
  cxse_language BLOB NOT NULL, cxse_wiki_family INTEGER UNSIGNED NOT NULL,
  cxse_page_title BLOB NOT NULL, cxse_section_titles BLOB NOT NULL,
  cxse_timestamp BLOB NOT NULL
);

CREATE UNIQUE INDEX cx_significant_edits_page ON /*_*/cx_significant_edits (
  cxse_global_user_id, cxse_page_wikidata_id,
  cxse_language, cxse_wiki_family
);


CREATE TABLE /*_*/cx_section_translations (
  cxsx_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cxsx_translation_id INTEGER UNSIGNED NOT NULL,
  cxsx_section_id BLOB NOT NULL, cxsx_source_section_title BLOB NOT NULL,
  cxsx_target_section_title BLOB NOT NULL,
  cxsx_translation_status SMALLINT DEFAULT NULL,
  cxsx_translation_progress BLOB NOT NULL,
  cxsx_translation_start_timestamp BLOB NOT NULL,
  cxsx_translation_last_updated_timestamp BLOB NOT NULL
);

CREATE UNIQUE INDEX cx_sx_sections ON /*_*/cx_section_translations (
  cxsx_translation_id, cxsx_section_id
);
