-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-cx_translations-index-translation_started_by_last_updated_timestamp.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE INDEX cx_translations_started_by_last_updated_timestamp ON /*_*/cx_translations (
  translation_started_by, translation_last_updated_timestamp
);
