-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ContentTranslation/sql/abstractSchemaChanges/patch-new-fields-to-cx_section_translations.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE  /*_*/cx_section_translations
ADD  cxsx_translation_status TINYINT(1) DEFAULT NULL,
ADD  cxsx_translation_progress TINYBLOB NOT NULL,
ADD  cxsx_translation_start_timestamp BINARY(14) NOT NULL,
ADD  cxsx_translation_last_updated_timestamp BINARY(14) NOT NULL;