-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-cx_suggestions-index-source_language_title.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE INDEX cx_suggestions_source_language_title ON /*_*/cx_suggestions (cxs_source_language, cxs_title);
