-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/ContentTranslation/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cx_translations (
  translation_id INT AUTO_INCREMENT NOT NULL,
  translation_source_title VARBINARY(512) NOT NULL,
  translation_target_title VARBINARY(512) NOT NULL,
  translation_source_language VARBINARY(36) NOT NULL,
  translation_target_language VARBINARY(36) NOT NULL,
  translation_source_revision_id INT UNSIGNED DEFAULT NULL,
  translation_target_revision_id INT UNSIGNED DEFAULT NULL,
  translation_source_url BLOB NOT NULL,
  translation_target_url BLOB DEFAULT NULL,
  translation_status ENUM('draft', 'published', 'deleted') DEFAULT NULL,
  translation_start_timestamp BINARY(14) NOT NULL,
  translation_last_updated_timestamp BINARY(14) NOT NULL,
  translation_progress TINYBLOB NOT NULL,
  translation_started_by INT DEFAULT NULL,
  translation_last_update_by INT DEFAULT NULL,
  translation_cx_version TINYINT UNSIGNED DEFAULT 1,
  UNIQUE INDEX cx_translation_ref (
    translation_source_title, translation_source_language,
    translation_target_language, translation_started_by
  ),
  INDEX cx_translation_languages (
    translation_source_language, translation_target_language,
    translation_status
  ),
  INDEX cx_translation_target_title (translation_target_title),
  PRIMARY KEY(translation_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cx_translators (
  translator_user_id INT NOT NULL,
  translator_translation_id INT NOT NULL,
  PRIMARY KEY(
    translator_user_id, translator_translation_id
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cx_lists (
  cxl_id INT AUTO_INCREMENT NOT NULL,
  cxl_type INT DEFAULT 0,
  cxl_owner INT NOT NULL,
  cxl_public TINYINT(1) NOT NULL,
  cxl_start_time BINARY(14) DEFAULT NULL,
  cxl_end_time BINARY(14) DEFAULT NULL,
  cxl_name VARBINARY(512) NOT NULL,
  cxl_info MEDIUMBLOB DEFAULT NULL,
  UNIQUE INDEX cx_lists_relevant (
    cxl_type, cxl_public, cxl_start_time,
    cxl_end_time
  ),
  PRIMARY KEY(cxl_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cx_suggestions (
  cxs_list_id INT NOT NULL,
  cxs_source_language VARBINARY(36) NOT NULL,
  cxs_target_language VARBINARY(36) DEFAULT NULL,
  cxs_title VARBINARY(512) NOT NULL,
  INDEX cx_suggestions_by_lang (
    cxs_list_id, cxs_source_language,
    cxs_target_language
  )
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cx_corpora (
  cxc_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cxc_translation_id INT NOT NULL,
  cxc_section_id VARBINARY(30) NOT NULL,
  cxc_origin VARBINARY(30) NOT NULL,
  cxc_sequence_id INT DEFAULT NULL,
  cxc_timestamp BINARY(14) DEFAULT NULL,
  cxc_content MEDIUMBLOB DEFAULT NULL,
  UNIQUE INDEX cx_corpora_unique (
    cxc_translation_id, cxc_origin, cxc_section_id,
    cxc_timestamp
  ),
  PRIMARY KEY(cxc_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cx_notification_log (
  cxn_id INT AUTO_INCREMENT NOT NULL,
  cxn_date BINARY(14) NOT NULL,
  cxn_newest BINARY(14) NOT NULL,
  cxn_wiki_id VARBINARY(64) DEFAULT NULL,
  INDEX cxn_wiki_id_newest (cxn_wiki_id, cxn_newest),
  PRIMARY KEY(cxn_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cx_significant_edits (
  cxse_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cxse_global_user_id INT UNSIGNED NOT NULL,
  cxse_page_wikidata_id INT UNSIGNED NOT NULL,
  cxse_language VARBINARY(36) NOT NULL,
  cxse_wiki_family INT UNSIGNED NOT NULL,
  cxse_page_title VARBINARY(255) NOT NULL,
  cxse_section_titles MEDIUMBLOB NOT NULL,
  cxse_timestamp BINARY(14) NOT NULL,
  UNIQUE INDEX cx_significant_edits_page (
    cxse_global_user_id, cxse_page_wikidata_id,
    cxse_language, cxse_wiki_family
  ),
  PRIMARY KEY(cxse_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/cx_section_translations (
  cxsx_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cxsx_translation_id INT UNSIGNED NOT NULL,
  cxsx_section_id VARBINARY(30) NOT NULL,
  cxsx_source_section_title VARBINARY(512) NOT NULL,
  cxsx_target_section_title VARBINARY(512) NOT NULL,
  cxsx_translation_status TINYINT(1) DEFAULT NULL,
  cxsx_translation_progress TINYBLOB NOT NULL,
  cxsx_translation_start_timestamp BINARY(14) NOT NULL,
  cxsx_translation_last_updated_timestamp BINARY(14) NOT NULL,
  UNIQUE INDEX cx_sx_sections (
    cxsx_translation_id, cxsx_section_id
  ),
  PRIMARY KEY(cxsx_id)
) /*$wgDBTableOptions*/;
